<?php


namespace App\Filters\Course;


use Illuminate\Database\Eloquent\Builder;
use App\Filters\FilterAbstract;

class AccessFilter extends FilterAbstract
{
    public function mappings()
    {
        $mappings = [
            'free' => true,
            'premium' => false,
        ];

        return $mappings; // TODO: Change the autogenerated stub
    }

    public function filter(Builder $builder, $value)
    {
        $value = $this->resolveFilterValue($value);

        if ($value === null)
        {
            return  $builder;
        }

        $item = $builder->where('free', $value);

        return $item;
    }
}
